################################################################################
# Default Variables.
################################################################################

.default_variables:

  ################################################################################
  # GENERAL VARIABLES
  ################################################################################

  CI_PHP_VERSION: "8.3"
  CI_NODE_VERSION: "22"
  CI_DRUPAL_VERSION: "10.3"
  CI_DRUPAL_WEB_ROOT: web
  CI_DOC_ROOT: "/builds/gealion1/books"
  CI_WEB_ROOT: "${CI_DOC_ROOT}/${CI_DRUPAL_WEB_ROOT}"
  CI_THEME_ROOT: "web/themes/custom/books"

  ################################################################################
  # QA VARIABLES
  ################################################################################
  CI_DIRS_QA_PHPCS: "${CI_WEB_ROOT}/**/custom"
  CI_DIRS_QA_PHPSTAN: "${CI_WEB_ROOT}/**/custom"

  CI_QA_IGNORE: "*/vendor/*,*/bootstrap/*,*/tests/*,*/.gitlab-ci/*,Readme.md,style.css,print.css,*Test.php"
  CI_QA_SUFFIX: "php,inc,module,install,test,profile,theme"
  #
  CI_QA_PHPCS_STANDARD: "Drupal,DrupalPractice"
  #
  CI_QA_CONFIG_PHPSTAN: ${CI_PROJECT_DIR}/phpstan.neon


  ################################################################################
  # CD VARIABLES
  ################################################################################
  PROD_SSH_HOST: "t148u_gealion@t148u.ftp.infomaniak.com"
  PORT_SSH_PORT: 22
  PROD_SSH_OPTIONS: ""
  PROD_PROJECT_REMOTE_DIR: "/home/clients/cb666d16fae465a663f9d2d948dd3b6e/sites/books.gealion.ch/current"
  PROD_PROJECT_REMOTE_WEBROOT: "current"
