################################################################################
# Default Variables.
################################################################################

.default_variables:

  ################################################################################
  # GENERAL VARIABLES
  ################################################################################

  CI_PHP_VERSION: "8.1"
  CI_DRUPAL_VERSION: "10.2"
  CI_DRUPAL_WEB_ROOT: web
  CI_DOC_ROOT: "/builds/corentin.bessire/books"
  CI_WEB_ROOT: "${CI_DOC_ROOT}/${CI_DRUPAL_WEB_ROOT}"

  ################################################################################
  # QA VARIABLES
  ################################################################################
  CI_DIRS_QA_PHPCS: "${CI_WEB_ROOT}/**/custom"
  CI_DIRS_QA_PHPSTAN: "${CI_WEB_ROOT}/**/custom"

  CI_QA_IGNORE: "*/vendor/*,*/bootstrap/*,*/tests/*,*/.gitlab-ci/*,Readme.md,style.css,print.css,*Test.php"
  CI_QA_SUFFIX: "php,inc,module,install,test,profile,theme"
  #
  CI_QA_PHPCS_STANDARD: "Drupal,DrupalPractice"
  #
  CI_QA_CONFIG_PHPSTAN: ${CI_PROJECT_DIR}/phpstan.neon


  ################################################################################
  # CD VARIABLES
  ################################################################################
  PROD_SSH_HOST: "ho7ser_system@ho7ser.ftp.infomaniak.com"
  PROD_PROJECT_REMOTE_DIR: "/home/clients/4f28a448d02a2707d2c962939cd91c23/sites/www.moudon.ch"
  PROD_URL: "https://www.moudon.ch/"


